### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by tavip**
I am preparing a jenkins builder to avoid some of the limitations of the circleci environment (e.g. lack of tun/tap support) and these patches fix a few issues to get "make test" reliably working.

---
This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/280)

### CODE REVIEW

**Comment by thehajime** [comment]
Introducing additional LKL_TEST_xxx is fine for me.

I think raw socket test is a handy way to test - in fact circle ci is able to test this even if tap/macvtap aren't available.

**Comment by tavip** [comment]
@thehajime I had trouble with the raw tests on my setups, but I think it was because of static assignment of IP address (the +10 IP address conflicted with something in my network).

I tried to use dhcp but for some reason that fails as well. I'll dig deeper and let you know.

But I would like to at least disable the static ip tests for macvlan/raw, as they can cause IP conflicts, unless I am missing something.

**Comment by thehajime** [comment]
> But I would like to at least disable the static ip tests for macvlan/raw, as they can cause IP conflicts, unless I am missing something.

Agree - indeed current net-test with static IP addr is somehow brittle...
The dhcp test is also not perfect I guess - with some of dhcp server, the current one isn't working well, but I couldn't spot those so far (circleci is still okay).

I'd like to propose to add LKL_TEST_RAW into circle.yml to enable the test.

**Comment by tavip** [comment]
@lkl-jenkins: retest this please

**Comment by tavip** [comment]
@lkl-jenkins: retest this please

**Comment by tavip** [comment]
@lkl-jenkins: retest this please

**Comment by tavip** [comment]
@lkl-jenkins: retest this please

**Comment by tavip** [comment]
@lkl-jenkins: retest this please

**Comment by tavip** [comment]
@lkl-jenkins: retest this please

**Comment by tavip** [comment]
@thehajime I've found a fix that seems to work well in all the environment (circle, jenkins, and my networks), please take a look at the latest commits.

I also think I've finished configuring the jenkins instance, sorry for all of the noise.

**Pull request merged**
