### PR TITLE
lkl tools: add symlink support to cptofs

### LINKED ISSUE #291: cptofs doesn't support symlinks
I cloned this repo (lkl/linux) to my local machine and attempted to use `cptofs` to copy it into a partitioned disk image as follows:

```
$ cptofs -i test.img -P 1 -t ext4 ~/linux /
skipping /home/ec2-user/linux/include/dt-bindings/input/linux-event-codes.h: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm64/boot/dts/include/dt-bindings: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm64/boot/dts/arm/vexpress-v2m-rs1.dtsi: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm64/boot/dts/socionext/uniphier-ref-daughter.dtsi: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm64/boot/dts/socionext/uniphier-pinctrl.dtsi: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm64/boot/dts/socionext/uniphier-support-card.dtsi: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm64/boot/dts/broadcom/bcm283x.dtsi: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm64/boot/dts/broadcom/bcm2835-rpi.dtsi: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm64/boot/dts/broadcom/bcm283x-rpi-smsc9514.dtsi: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/cris/boot/dts/include/dt-bindings: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm/boot/dts/include/dt-bindings: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm/boot/dts/sun8i-a33-et-q8-v1.6.dts: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm/boot/dts/sun8i-a23-ippo-q8h-v1.2.dts: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm/boot/dts/sun8i-a33-ippo-q8h-v1.2.dts: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/arm/boot/dts/sun8i-a23-ippo-q8h-v5.dts: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/powerpc/boot/dts/include/dt-bindings: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/metag/boot/dts/include/dt-bindings: unsupported entry type 40960
skipping /home/ec2-user/linux/arch/mips/boot/dts/include/dt-bindings: unsupported entry type 40960
skipping /home/ec2-user/linux/README.md: unsupported entry type 40960
skipping /home/ec2-user/linux/tools/testing/selftests/powerpc/primitives/word-at-a-time.h: unsupported entry type 40960
skipping /home/ec2-user/linux/tools/testing/selftests/powerpc/primitives/asm/asm-compat.h: unsupported entry type 40960
skipping /home/ec2-user/linux/tools/testing/selftests/powerpc/stringloops/memcmp_64.S: unsupported entry type 40960
skipping /home/ec2-user/linux/tools/testing/selftests/powerpc/copyloops/memcpy_power7.S: unsupported entry type 40960
skipping /home/ec2-user/linux/tools/testing/selftests/powerpc/copyloops/copyuser_power7.S: unsupported entry type 40960
skipping /home/ec2-user/linux/tools/testing/selftests/powerpc/copyloops/copyuser_64.S: unsupported entry type 40960
skipping /home/ec2-user/linux/tools/testing/selftests/powerpc/copyloops/memcpy_64.S: unsupported entry type 40960
skipping /home/ec2-user/linux/tools/testing/selftests/powerpc/vphn/vphn.c: unsupported entry type 40960
skipping /home/ec2-user/linux/tools/testing/selftests/powerpc/vphn/vphn.h: unsupported entry type 40960
```

~~The "unsupported entry type" message seems to be produced by something related to `tar`~~, but I'm not sure what it means beyond that. Anyone know what's up and whether it's a `cptofs` bug or just PEBKAC?

### PR DESCRIPTION
**Pull request by copumpkin**
This should fix #291. I tried to replicate the style used in cptofs.c but this is my first commit to the project so please let me know if I missed something!

I was tempted to make `stat_src` just take a `struct stat` pointer rather than adding another pointer parameter, but then I'd have to copy the fields from `lkl_stat` into it and this seemed slightly cleaner.

---
This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/294)

### CODE REVIEW

**Comment by copumpkin** [comment]
Actually, I'm seeing some weirdness with `cpfromfs`. Will investigate and possibly update the PR.

**Comment by tavip** [comment]
@lkl-jenkins: test this please

**Comment by copumpkin** [comment]
@tavip I couldn't actually find a test for `cptofs`, so I didn't add any automated tests that explicitly checked whether symlinks worked. Is there somewhere I should put such a thing?

**Comment by tavip** [comment]
@copumpkin With regards to tests, if you can add something in tools/lkl/tests (maybe cptofs.sh?), it would be great !

**Comment by copumpkin** [comment]
@tavip can I fix checkpatch issues and then submit a separate PR for tests for `cptofs`? I'd prefer to keep the PRs fairly self-contained

**Comment by copumpkin** [comment]
Fixed checkpatch issues!

**Comment by tavip** [comment]
> can I fix checkpatch issues and then submit a separate PR for tests for cptofs? I'd prefer to keep the PRs fairly self-contained

Of course, that is the way I would prefer it too. Thanks!

**Comment by tavip** [comment]
@lkl-jenkins: test this please

**Comment by copumpkin** [comment]
(as an aside, is there an LKL IRC channel or other chat community somewhere I can go idle?)

**Comment by copumpkin** [comment]
Thanks!

**Comment by Rondom** [comment]
@copumpkin There is a [mailing list](https://github.com/lkl/linux/blob/6c7ad3eab1ad1820b2b210861335317a719dbd0a/MAINTAINERS#L7326). Besides that @thehajime and I idle in #lkl at FreeNode, but so far we are the only ones and have not really pursued the idea of creating an "official" channel any further...

**Pull request merged**
