### PR TITLE
lkl: Add irq counter to record number of irq triggered.

### PR DESCRIPTION
**Pull request by liuyuan10**
This can avoid irq miss.

Signed-off-by: Yuan Liu liuyuan@google.com

---

This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/174)

### CODE REVIEW

**Comment by tavip** [comment]
Did you see some improvements using this approach? It was the initial approach I used, but switched to the current one because missing of interrupts do happen on real hardware, and it does not help to run the irq handlers twice.

**Comment by liuyuan10** [comment]
No improvement observed. What I really want is to avoid run_irqs in arch_local_irq_restore which can boost performance on top of PR #160 (If not on top of PR #160, doing so will cause TCP_RR degrade). For example, I may choose to run irqs on syscall entrance/exit. That can delay irq handling and cause more irq misses. What I'm worried about is timer irq misses which can delay timers in LKL. This PR can let the LKL timers quickly catchup in one call of run_irqs and alleviates irq misses (but not solves it).

**Comment by tavip** [comment]
I don't think running the timer interrupt multiple times is necessary to catch up the timers. IIUC, at least when using NO_IDLE, the clock source driver should be used to correct the time at the first run of the irq handler.

**Comment by liuyuan10** [comment]
You are right. LKL is using the lkl clocksource instead of jiffies to adjust time in timer irq handler. I don't see a reason for this PR anymore.

**Pull request closed without merging**
