### PR TITLE
Merge mainline v6.4

### PR DESCRIPTION
**Pull request by ddiss**
Only a few minor changes needed for the merge

### CODE REVIEW

**Comment by ddiss** [comment]
Looks like I need to go through some of the test failures first before proceeding further. Flagging as draft.

**Comment by tavip** [comment]
Thanks for the PR @ddiss ! I suspect the CI issues are due to something missing with the clang integration. Nothing obvious to me at first glance, maybe  @rodionov  can spot something?

**Comment by ddiss** [comment]
> Thanks for the PR @ddiss ! I suspect the CI issues are due to something missing with the clang integration. Nothing obvious to me at first glance, maybe @rodionov can spot something?

Thanks @tavip ! Assistance with the CI issues would be much appreciated, as my local environment doesn't currently run the entire LKL test suite.
The minor v2 update I just pushed has the following modifications:
- drop lkl/tests/disk.c parameter check, which isn't relevant for v6.4 (will submit separately)
- fix checkpatch complaints

**Comment by rodionov** [comment]
>  Thanks for the PR @ddiss ! I suspect the CI issues are due to something missing with the clang integration. Nothing obvious to me at first glance, maybe @rodionov can spot something?

Indeed, there are some minor changes to `scripts/Makefile.clang` which might break integration with clang. Investigating this.

**Comment by rodionov** [comment]
@ddiss this one-liner for `tools/lkl/Makefile.autoconf` should fix the problem with `clang-build` and `lkl-fuzzers` build targets:

```
diff --git a/tools/lkl/Makefile.autoconf b/tools/lkl/Makefile.autoconf
index a15753193a4f..fc47f12a3093 100644
--- a/tools/lkl/Makefile.autoconf
+++ b/tools/lkl/Makefile.autoconf
@@ -166,7 +166,7 @@ endef
 define do_autoconf_llvm
   $(eval LLVM_PREFIX := $(if $(filter %/,$(LLVM)),$(LLVM)))
   $(eval LLVM_SUFFIX := $(if $(filter -%,$(LLVM)),$(LLVM)))
-  export CROSS_COMPILE := $(CROSS_COMPILE)
+  export CLANG_TARGET_FLAGS_lkl := $(CROSS_COMPILE)
   export CC := $(LLVM_PREFIX)clang$(LLVM_SUFFIX)
   export LD := $(LLVM_PREFIX)ld.lld$(LLVM_SUFFIX)
   export AR := $(LLVM_PREFIX)llvm-ar$(LLVM_SUFFIX)
```

Due to some changes in `scripts/Makefile.clang` it no longer uses `CROSS_COMPILE` variable to pass `--target=` argument to llvm toolchain. Instead, it is using `CLANG_TARGET_FLAGS_$(SRCARCH)` which effectively is `CLANG_TARGET_FLAGS_lkl`.

Regarding kasan tests it's still not clear why it is failing.

**Comment by tavip** [comment]
Quick update on kasan test failure: kasan kunit tests have switch to tracepoints in 7ce0ea19d50e4e97a8da69f616ffa8afbb532a93 and LKL currently does not support tracepoints. Still looking into what it would take to implement tracepoint support for LKL.

**Comment by ddiss** [comment]
@rodionov thanks - I've pushed a new commit with your proposed Makefile.autoconf change.

**Comment by zouyonghao** [comment]
Is it possible to add a new branch or a tag for each Linux release?

**Comment by ddiss** [comment]
> Is it possible to add a new branch or a tag for each Linux release?

I think a signed tag (e.g. `lkl-vX.Y`) where `X.Y` matches the corresponding mainline tag would be nice to have.
Branching for each release would be a bit confusing IMO; it might be interpreted as indicating ongoing maintenance for old versions.

**Comment by ddiss** [comment]
> Quick update on kasan test failure: kasan kunit tests have switch to tracepoints in [7ce0ea1](https://github.com/lkl/linux/commit/7ce0ea19d50e4e97a8da69f616ffa8afbb532a93) and LKL currently does not support tracepoints. Still looking into what it would take to implement tracepoint support for LKL.

@tavip any luck finding out what's needed for LKL tracepoints? I'm a bit clueless when it comes to tracepoint support, so would greatly appreciate any guidance you could offer.

**Comment by thehajime** [comment]
@ddiss @tavip @rodionov   long time no see you all...

> > Quick update on kasan test failure: kasan kunit tests have switch to tracepoints in [7ce0ea1](https://github.com/lkl/linux/commit/7ce0ea19d50e4e97a8da69f616ffa8afbb532a93) and LKL currently does not support tracepoints. Still looking into what it would take to implement tracepoint support for LKL.
> 
> @tavip any luck finding out what's needed for LKL tracepoints? I'm a bit clueless when it comes to tracepoint support, so would greatly appreciate any guidance you could offer.

I did a quick look and the following diff makes the kasan-test failure gone.


```
diff --git a/arch/lkl/Kconfig b/arch/lkl/Kconfig
index cb319652ff49..915b5400bbbd 100644
--- a/arch/lkl/Kconfig
+++ b/arch/lkl/Kconfig
@@ -41,6 +41,9 @@ config LKL
        select GENERIC_STRNCPY_FROM_USER
        select GENERIC_STRNLEN_USER
        select HAVE_ARCH_KASAN
+       select TRACING
 
 config LKL_FUZZING
        bool "LLVM fuzzing instrumentation"
diff --git a/tools/lkl/tests/boot.c b/tools/lkl/tests/boot.c
index d8601306ac34..118903dc68bd 100644
--- a/tools/lkl/tests/boot.c
+++ b/tools/lkl/tests/boot.c
@@ -511,7 +511,7 @@ static int lkl_test_kasan(void)
 
        line = strtok(log, "\n");
        while (line) {
-               if (sscanf(line, "[ %*f] ok %*d - kasa%c%c", &c, &d) == 1 &&
+               if (sscanf(line, "[ %*f] ok %*d kasa%c%c", &c, &d) == 1 &&
                           c == 'n') {
                        lkl_test_logf("%s", line);
                        return TEST_SUCCESS;
```

One thing that I don't understand is the format difference of kasan test report.  I cannot spot where it is coming from...
With the older version, it generates

```
  [    0.661363] # kasan: pass:43 fail:0 skip:13 total:56
  [    0.661367] # Totals: pass:43 fail:0 skip:13 total:56
  [    0.661371] ok 1 - kasan
```

while the new one does

```
  [    0.779125] # kasan: pass:45 fail:0 skip:13 total:58
  [    0.779131] # Totals: pass:45 fail:0 skip:13 total:58
  [    0.779137] ok 1 kasan
```

(with `-` or not)

Hope this helps this PR move forward.

**Comment by ddiss** [comment]
@thehajime it's great to hear from you and thanks for the patch!
Would you mind if I add it as a separate commit with your authorship / sign off to this PR?

**Comment by thehajime** [comment]
https://github.com/thehajime/linux/commit/d66e6c0dfc43cc46240f05d41534c7c3844c68ae

Yes, you can pick it from above.

**Comment by ddiss** [comment]
> [thehajime@d66e6c0](https://github.com/thehajime/linux/commit/d66e6c0dfc43cc46240f05d41534c7c3844c68ae)
> 
> Yes, you can pick it from above.

Done. I've also updated @rodionov 's Makefile.autoconf commit to include an author sign off as per https://github.com/lkl/linux/pull/530#issuecomment-1715240346 .

**Comment by thehajime** [comment]
lgtm.  Would wait for @tavip @rodionov for the review.

**Comment by tavip** [comment]
LGTM, thanks @thehajime for tracking this down!

**Comment by rodionov** [comment]
LGTM. Thanks, folks!

**Comment by thehajime** [comment]
thanks all !
I'll take a look at further upstreams (6.6, longterm one especially) in my spare time.

**Pull request merged**
