### PR TITLE
lkl: Turn on epoll; test pipe2 + epoll

### PR DESCRIPTION
**Pull request by pscollins**
This commit also includes a few "cleanup" changes in
tools/lkl/tests/boot.c, to make the intent of the test code more clear
(e.g. ambiguity of 0 as success or failure replaced by a macro).

Signed-off-by: Patrick Collins pscollins@google.com

[Review on Reviewable](https://reviewable.io/reviews/lkl/linux/50)

### CODE REVIEW

**Comment by pscollins** [comment]
Whoops, I guess Windows doesn't have `strerror_r`. I'll fix it up in a minute.

**Comment by stfairy** [comment]
You may also split it into three commits
1. cleanup
2. pipe test
3. epoll

**Comment by stfairy** [comment]
Btw, were you able to run an epoll program with the hijack stuff?  I somehow got:
```
epoll_ctl: Success
```
from `perror`.

**Comment by pscollins** [comment]
@stfairy I didn't try any of the hijack stuff. I'll take a look at that after I clean this one up.

**Comment by thehajime** [comment]
the patch itself looks good to me.

for epoll  app on hijack lib, it would be great if you give me how to reproduce it. an quick try on my local machine doesn't give me the error.

**Comment by opurdila** [comment]
Thanks Patrick !

**Comment by stfairy** [comment]
@thehajime It was actually caused by passing a non-LKL fd to epoll_ctl.  So I guess epoll per se is good to use.

**Comment by thehajime** [comment]
@stfairy okay.

**Pull request merged**
