### PR TITLE
lkl: Add host operation for calloc

### PR DESCRIPTION
**Pull request by pscollins**
Signed-off-by: Patrick Collins pscollins@google.com

[Review on Reviewable](https://reviewable.io/reviews/lkl/linux/85)

### CODE REVIEW

**Comment by opurdila** [comment]
Can you please give me more context on why is this needed?

**Comment by pscollins** [comment]
@opurdila I use it in a future PR; I've been splitting off simple stuff like this so that simple changes don't clutter up review of more complicated code. I use it in a spot that looks like:

```
struct lkl_mutex_t **mutexes = lkl_host_ops.calloc(n_queues, sizeof(struct lkl_mutex_t*));
if (!mutexes)
    goto fail;

for (int i = 0; i < n_queues; i++) {
    mutexes[i] = lkl_host_ops.mutex_alloc();
    if(!mutexes[i])
        goto fail_all;
} 

return mutexes;

fail_all:
for (int i = 0; i < n_queues; i++) {
    free(mutexes[i]);
}
fail:
free(mutexes)

return NULL;
```

because it makes the error handling simpler (no need to track what `i` the `mutex_alloc()` failed on, but a `memset` right after the `malloc` might cause a segfault).

**Comment by opurdila** [comment]
@pscollins Hmm, we can still do the memset after the "if (!mutexes)" check.

I feel that adding host operation like calloc is a bit overkill and that it complicates adding support for a new hosts.

This reminds me of one thing I wanted to comment on the mutex patch: mutex operations should be optional and we should provide generic mutex operations based on semaphores, i.e. in lkl_start_kernel we should check for NULL mutex ops and implement them with semaphores if needed. In this way we can make it easy to add support for a new host, initially, and we can optimize it later.

**Comment by thehajime** [comment]
again, I'm second to @opurdila, I would like to keep host ops as minimum as possible (i.e., memory management, scheduling, and clock source are minimum set of host os I believe).

**Comment by pscollins** [comment]
@opurdila @thehajime 

Regarding mutexes --- I think that will make the arch code more complicated than necessary; better to ask the person implementing a new host to implement mutexes with semaphores in their `mutex_*` functions. Even if it's just a semaphore behind the scenes, in the arch code it gives you more intention-revealing names, more type safety, reduces the number of `#ifdef`s you need, etc, and the complexity is limited to the `foo-host.c` files. The host should be responsible for providing abstractions, and the rest of the codebase can trust that they work. 

`calloc` is in `stdlib.h` and it's part of the C99 and C89 standard; any host that doesn't support it doesn't have a spec-conforming C compiler. Conceivably there is an embedded system somewhere that doesn't support it, but that kind of host probably has much bigger problems. In that case, for that host, we can just define it in one place as `malloc` + `memset` rather than spreading the complexity throughout the rest of the codebase. IMO we should expose as much of the host standard library as possible, so it's easy to write C naturally, without having to re-implement stdlib features.

**Comment by thehajime** [comment]
> In that case, for that host, we can just define it in one place as malloc + memset rather than spreading the complexity throughout the rest of the codebase. 

for the specific ```calloc``` case, what about creating a wrapper on lkl side (not host side) something like tools/lkl/lib/utils.c ? it would be a single malloc+memset and more easier than doing for *n kind of hosts.

> IMO we should expose as much of the host standard library as possible, so it's easy to write C naturally, without having to re-implement stdlib features.

this is somewhat off-topic, but I'm working on frankenlibc (originally by @justincormack) for exactly the same motivation (i.e., write C naturally when implementing host_ops (in frankenlibc term it's hypercall)).

I think I need more careful discussion before upstreaming or a PR so I will be back later (tm).

https://github.com/libos-nuse/frankenlibc

**Comment by pscollins** [comment]
> it would be a single malloc+memset 

I think we should avoid re-implementing parts of the standard library unless it is absolutely necessary.

> more easier than doing for *n kind of hosts.

I have a refactor in mind that splits off stdlib functions into a `common-host.c` file, and then `host_ops.h` looks like:

```
struct lkl_stdlib_ops {
    void *(*mem_alloc)(unsigned long);
    void (*mem_free)(void *);
    void (*lkl_printf)(const char*, ...);
    void (*panic)(void);
   
    // etc -- plus whatever else. I'd pull in calloc and realloc right away.
};

extern struct lkl_stdlib_ops lkl_stdlib_ops;

struct lkl_host_ops lkl_host_ops = {
    struct lkl_stdlib_ops lkl_stdlib_ops_;
    #define mem_alloc lkl_stdlib_ops_.mem_alloc
    #define mem_free lkl_stdlib_ops_.mem_free
    #define panic lkl_stdlib_ops_.panic
    #define lkl_printf lkl_stdlib_ops_.lkl_printf
    // etc
}
```

With `common-host.c`:

```
#include <stdlib.h>
#include <assert.h>

void panic(void)
{
    assert(0);
}
// etc
struct lkl_stdlib_ops lkl_stdlib_ops = {
    .malloc = mem_alloc,
    .free = mem_free,
    .lkl_printf = printf,
    .panic = panic,
};
```

Now the duplication is gone, we've put all of the things that are required by the C spec together without making the API any messier, and we're guaranteed that any host that implements C can compile `common-host.c`. I can put together a PR if you all (@thehajime @opurdila @stfairy ?) approve. 

It's a large-ish change and I'm not sure it's 100% justified for the sake of code cleanliness since we only have two flavors of host right now (and it's hard to think when we'd want more than Winw32 and POSIX), but IMO it's better to pull these things together so it's easy to provide access to them than it is to re-implement them unnecessarily.

**Comment by opurdila** [comment]
It may be a good thing to do. But note that we only need these ops if we are going to use them in the kernel side of things. On host libs side we can directly use malloc/realloc/etc.

And one word of caution: using #define mem_alloc will interact with the headers_install script and will probably get rename to lkl_mem_alloc etc.

**Comment by pscollins** [comment]
@opurdila Hmm, that's true, I guess the scope is smaller than I thought. I still think it would be nice to stick it in the current setup as another host op, but if you don't want to do that, then I guess it's not worth the trouble.

**Pull request closed without merging**
