### PR TITLE
lkl: Fix missing screen_info during compilation.

### PR DESCRIPTION
**Pull request by ngkaho1234**
#88

[Review on Reviewable](https://reviewable.io/reviews/lkl/linux/109)

### CODE REVIEW

**Comment by pscollins** [comment]
LGTM

**Comment by opurdila** [comment]
@ngkaho1234 so can we remove the screen_info define then and only keep the Kconfig "ban" ?

**Comment by ngkaho1234** [comment]
@opurdila  Then we have to ban both VGA_CONSOLE and DUMMY_CONSOLE

**Comment by opurdila** [comment]
@ngkaho1234 I think that is fine. We certainly can't use VGA_CONSOLE. Do you see any usage for DUMMY_CONSOLE in LKL, I am not familiar with it?

**Comment by ngkaho1234** [comment]
@opurdila Maybe we just ban both of them, since DUMMY_CONSOLE doesn't make any effects at all.

**Comment by opurdila** [comment]
@ngkaho1234 OK, lets to that. Thanks !

**Comment by ngkaho1234** [comment]
@opurdila However one of XXX_CONSOLE has to be enabled, otherwise writing to .config will likely fail.

**Comment by ngkaho1234** [comment]
@opurdila OK i found another solution, which is to ban CONFIG_VT

**Pull request merged**
