### PR TITLE
lkl: Add a debug utility to access LKL file system.

### PR DESCRIPTION
**Pull request by liuyuan10**
By hitting Ctrl-Z, it provides a fake cmd line of lkl kernel. So one can
check /proc, /sysfs etc for debuging purpose. More cmds can be added to
satisfy individual need.

TESTED:
 LKL_HIJACK_DEBUG=1 bin/lkl-hijack.sh sleep 100

Signed-off-by: Yuan Liu liuyuan@google.com

---

This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/162)

### CODE REVIEW

**Comment by liuyuan10** [comment]
We are having this utility in our local branch. Let me know if it's needed by upstream.

**Comment by liuyuan10** [comment]
Looks like the usage of signal.h is not portable. I can make it posix only it it's needed. Let me know.

**Comment by thehajime** [comment]
i have tried and feel so nice !
it would be beneficial to include in upstream.

a couple of high-level comment;

- can I resume the suspended process ?
- it would be nice to handle signal on mingw (i hope there is a workaround)
- if I failed by `mount procfs`, a directory entry remains at ```/procfs```. ```mount proc``` works fine.

I will give another code review; hopefully in early next week.

**Comment by pscollins** [comment]
I don't have much to say about the code since I haven't looked at LKL too much lately -- but wow, it's amazing that you guys got a shell working inside LKL. I'm sure this opens the way to build a lot of new tools.

**Comment by liuyuan10** [comment]
> can I resume the suspended process ?
Actually the process is not suspended at all. The dbg session runs in a separate host thread.
> it would be nice to handle signal on mingw (i hope there is a workaround)
I don't have a mingw to test it and it may take me quite a while. I will leave it there hoping someone good at windows may want to fill the gap.
> if I failed by mount procfs, a directory entry remains at /procfs. mount proc works fine.
fixed.

**Comment by thehajime** [comment]
@opurdila I think this patch is ready for merge.  can fix the issue on win32 later if someone is interested in.

**Pull request merged**
