### PR TITLE
lkl: cleanup

### PR DESCRIPTION
**Pull request by thehajime**
first round of clean up including quiet warnings and make test for internal exercise using circleci.

### CODE REVIEW

**Comment by tavip** [comment]
Hi Hajime,

I've just merged the freebsd patches into master, so I had to rebase you patches, see the hajime_cleanup branch.

I kept the warnings in checksyscalls.sh for the system calls that we don't have yet implemented but we can implement.

If it looks ok to you, I will merge it in the master branch.

Thanks,
Tavi

**Comment by thehajime** [comment]
> I kept the warnings in checksyscalls.sh for the system calls that we don't have yet implemented but we can implement.

Okay. agree.

> If it looks ok to you, I will merge it in the master branch.

what about the commits about 'make test' and CircleCI ?
This will be so helpful since you can check any pull requests by building/testing the patchset before a merge.

**Comment by tavip** [comment]
>what about the commits about 'make test' and CircleCI ?
>This will be so helpful since you can check any pull requests by building/testing the patchset before a merge.

They should be in that branch. Or am I missing something?

**Comment by thehajime** [comment]
> They should be in that branch. Or am I missing something?

you're completely right, my bad, I was looking different diff....

so, I'm fine with the branch. 
+1

**Comment by tavip** [comment]
Merged, thanks Hajime!

**Pull request closed without merging**
