### PR TITLE
lkl doc: Fix build instructions on Ubuntu

### PR DESCRIPTION
**Pull request by gbitten**
Update the instructions to run tests on Ubutnu

---
This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/460)

### CODE REVIEW

**Comment by thehajime** [comment]
Thanks @gbitten.  LGTM.  To solve the checkpatch error, please add a Signed-off-by line in the commit message.

**Comment by gbitten** [comment]
> Thanks @gbitten. LGTM. To solve the checkpatch error, please add a Signed-off-by line in the commit message.

Ok, I think it is ok now.

**Comment by thehajime** [comment]
sorry, there is still an error on checkpatch.

you may wish to 1) rebase your branch to the master (`git rebase lkl/master`), 2) squash several commits into a single one, 3) then put Signed-off-by line in the commit log (squashed one).

**Comment by gbitten** [comment]
I hope I did it correctly.

**Comment by thehajime** [comment]
thanks !

**Pull request merged**
