### PR TITLE
Add mount/dump functionality

### PR DESCRIPTION
**Pull request by pscollins**
This series of commits adds some extra functionality to help examine the state of LKL when it exits.

The number of environment variables LKL reads from is starting to get a little out of control, but I can't think of a better way to do it right now.

[Review on Reviewable](https://reviewable.io/reviews/lkl/linux/90)

### CODE REVIEW

**Comment by thehajime** [comment]
Looks nice !

I'll give more review but one comment on many env variables. We may want to have a document to describe what env are available. 

Maybe in README ?

**Comment by pscollins** [comment]
@thehajime Yes, that sounds good to me

**Comment by thehajime** [comment]
I will create an issue for the documentation.

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lkl/lib/hijack/init.c, line 1 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/90#-KBPyAlsRWrQ0FjpQUB5:-KBPyAlsRWrQ0FjpQUB6:-1540208597) ([raw file](https://github.com/lkl/linux/blob/055b05871e75cfa9b5532ac290782d9c927345cc/tools/lkl/lib/hijack/init.c#L1)):*
pls delete unnecessary newline.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/lkl/linux/90#-:-KBPzCOnQRux0NntjVld:-1860353566)*

**Comment by thehajime** [comment]
don't forget to add the document (#95).

**Pull request merged**
