### PR TITLE
use host_task_stub() for host task

### PR DESCRIPTION
**Pull request by laijs**
Signed-off-by: Lai Jiangshan <jiangshanlai@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/322)

### CODE REVIEW

**Comment by liuyuan10** [comment]
Why do you need this?

**Comment by laijs** [comment]
better readability

**Comment by tavip** [comment]
I am not sure it is better in terms of readability, as we don't ever run the stub function as passing it to the kernel_thread() call implies. So you still need to check the implementation in copy_thread() at which point passing NULL or the stub function is kind the same to me.

That being said, I don't have a strong opinion on this, and if other people think is better I'll merge it :)

**Comment by laijs** [comment]
kernel may uses sp=NULL in _do_fork() in other cases. we don't need to check everywhere every case (now or in future) when we use a stub function.

**Comment by tavip** [comment]
@lkl-jenkins: test this please

**Pull request merged**
