### PR TITLE
lkl: Add a config option to select section for kallsyms

### PR DESCRIPTION
**Pull request by andreas-abel**
Added a config option to select the section for kallsyms, and set .data section as the default for LKL.

See issue #220.

Signed-off-by: Andreas Abel aabel@google.com

---

This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/221)

### CODE REVIEW

**Comment by liuyuan10** [comment]
Thanks Andreas. The change looks good to me. Some comments on the commit msg:
1. Please put "lkl:" before the title
2. Please write down some simple works describing the commit in the commit msg
3. Please add your sign-off

**Comment by opurdila** [comment]
Something went wrong with the last push, I see three commits (one being a merge commit). 

I also suggest adding more info in the commit message, e.g. https://github.com/opurdila/linux/commit/b97c7d97a628285fef70164b528085e4ae4b72f6.

To make this easier to accept upstream, It would be good to change the .rodata -> .data behaviour only if we pass a new option to kallsym and update scripts/link-vmlinux.sh accordingly.

**Comment by andreas-abel** [comment]
Thanks for the helpful suggestions, @opurdila and @liuyuan10!

I have now added a new option CONFIG_KALLSYMS_USE_DATA_SECTION to select the section for kallsyms, and set the .data section as default for LKL, and the .rodata section as default for all other architectures.

**Comment by liuyuan10** [comment]
LGTM

**Pull request merged**
