### PR TITLE
 lkl: Fix ipv6 netperf failure 

### PR DESCRIPTION
**Pull request by liuyuan10**
ipv6 address is in state tentative until Duplicate Address Detection
(DAD) is done. So netperf can't get the correct ip address on LKL
startup.

Fixed by waiting for binding on the ipv6 address succeed.

---

This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/197)

### CODE REVIEW

**Comment by thehajime** [comment]
what about inserting `sleep(time)` at the end of `hijack_init()` where the variable `sleep` is configured by something like `LKL_HIJACK_SLEEP_SECOND` instead of disabling DAD ?

I think hard-coded disabling feature is not  a good idea in general if there is someone who needs the feature.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/197#-:-KOk1YNeqt8SBwK2RBA_:b1ucgid)*

**Comment by liuyuan10** [comment]
sleep works too. But to make it safe, 5 sec is something reasonable. Then the test time is not acceptable. Now there are ~10 tap tests. All those 5 sec can add up to a min. No reason to wait for a min. I added a LKL_HIJACK_NET_NO_DAD to control DAD specifically. PTAL

**Comment by liuyuan10** [comment]
I changed it to wait for ipv6 ready by using sys_bind. So it can continue as soon as dad is done.

**Comment by opurdila** [comment]
Reviewed 3 of 4 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lkl/lib/fs.c, line 14 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/197#-KOvjBnWnVloMqaKzRih:-KOvjBnWnVloMqaKzRii:b-grahdr) ([raw file](https://github.com/lkl/linux/blob/7f829eef3283a8cceb848e8c4d8565885edd0063/tools/lkl/lib/fs.c#L14)):*
> ```C
> 
> 	/* Create with regular umask */
> 	ret = lkl_sys_mkdir(dir, 0xff);
> ```

We need to check if the fs was already mounted, otherwise this is going to fail and so will get_virtio_blkdev.

---

*[tools/lkl/lib/hijack/init.c, line 188 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/197#-KOvlRmOt4M2hfZJeJoe:-KOvlRmOt4M2hfZJeJof:b4vfp0s) ([raw file](https://github.com/lkl/linux/blob/7f829eef3283a8cceb848e8c4d8565885edd0063/tools/lkl/lib/hijack/init.c#L188)):*
> ```C
> 
> // Returns 0 on success.
> int wait_ipv6(const struct in6_addr *addr, unsigned int timeout_sec) {
> ```

I think we can wait for a reply netlink message when setting up the ipv6 address instead of this. AFAICS we will receive a netlink message when the DAD is complete:

$ ip monitor all

# first message receive, imediately after the IPv6 address is added
[nsid current]fc03::2 dev wlp3s0  proto kernel  metric 256  pref medium

# messages received after DAD completed
[nsid current]3: wlp3s0    inet6 fc03::2/128 scope global 
       valid_lft forever preferred_lft forever
[nsid current]local fc03::2 dev lo  table local  proto none  metric 0  pref medium

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/197)*

**Comment by thehajime** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lkl/lib/hijack/init.c, line 188 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/197#-KOvlRmOt4M2hfZJeJoe:-KP-qn8MHjLHba_uBtpy:b21dzno) ([raw file](https://github.com/lkl/linux/blob/7f829eef3283a8cceb848e8c4d8565885edd0063/tools/lkl/lib/hijack/init.c#L188)):*
<details><summary><i>Previously, opurdila (Octavian Purdila) wrote…</i></summary>
> I think we can wait for a reply netlink message when setting up the ipv6 address instead of this. AFAICS we will receive a netlink message when the DAD is complete:
> 
> $ ip monitor all
> 
> # first message receive, imediately after the IPv6 address is added
> [nsid current]fc03::2 dev wlp3s0  proto kernel  metric 256  pref medium
> 
> # messages received after DAD completed
> [nsid current]3: wlp3s0    inet6 fc03::2/128 scope global 
>        valid_lft forever preferred_lft forever
> [nsid current]local fc03::2 dev lo  table local  proto none  metric 0  pref medium
> 
</details>
I think using a netlink notification looks smarter.  it would be also great if it will be done inside lkl_if_set_ipv6().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/197)*

**Comment by liuyuan10** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lkl/lib/fs.c, line 14 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/197#-KOvjBnWnVloMqaKzRih:-KP4ZpkW-o0DAkPFgVTI:blvomj8) ([raw file](https://github.com/lkl/linux/blob/7f829eef3283a8cceb848e8c4d8565885edd0063/tools/lkl/lib/fs.c#L14)):*
<details><summary><i>Previously, opurdila (Octavian Purdila) wrote…</i></summary>
> We need to check if the fs was already mounted, otherwise this is going to fail and so will get_virtio_blkdev.
</details>
I think I already handled the case. This function returns 1 if it's mounted already.

---

*[tools/lkl/lib/hijack/init.c, line 188 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/197#-KOvlRmOt4M2hfZJeJoe:-KP5Mcnj08q0Hy9lg7oM:b-lvibsb) ([raw file](https://github.com/lkl/linux/blob/7f829eef3283a8cceb848e8c4d8565885edd0063/tools/lkl/lib/hijack/init.c#L188)):*
<details><summary><i>Previously, thehajime (Hajime Tazaki) wrote…</i></summary>
> I think using a netlink notification looks smarter.  it would be also great if it will be done inside lkl_if_set_ipv6().
</details>
This is a good idea. changed to use netlink.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/197)*

**Comment by opurdila** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/lkl/lib/fs.c, line 14 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/197#-KOvjBnWnVloMqaKzRih:-KP5OU_QfFeomifvpIdD:b-y0r9ra) ([raw file](https://github.com/lkl/linux/blob/7f829eef3283a8cceb848e8c4d8565885edd0063/tools/lkl/lib/fs.c#L14)):*
<details><summary><i>Previously, liuyuan10 (Yuan Liu) wrote…</i></summary>
> I think I already handled the case. This function returns 1 if it's mounted already.
</details>
Hm, maybe I am missing something, but if we already mounted the fs, then we already created the directory and lkl_sys_mkdir above is going to fail.

---

*[tools/lkl/lib/net.c, line 388 \[r3\]](https://reviewable.io:443/reviews/lkl/linux/197#-KP5OxnrITDyEzQMgB62:-KP5OxnrITDyEzQMgB63:bahvtrx) ([raw file](https://github.com/lkl/linux/blob/2276fa72daaf65ca03d68b8becac20a701a617be/tools/lkl/lib/net.c#L388)):*
> ```C
> 		return err;
> 
> 	err = wait_ipv6(ifindex, addr);
> ```

I think there is a race condition here, if DAD completed before we call wait_ipv6 we will hang here forever.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/197)*

**Comment by liuyuan10** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/lkl/lib/fs.c, line 14 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/197#-KOvjBnWnVloMqaKzRih:-KP5ZPELMcsx_-rJPc-L:brkp21l) ([raw file](https://github.com/lkl/linux/blob/7f829eef3283a8cceb848e8c4d8565885edd0063/tools/lkl/lib/fs.c#L14)):*
<details><summary><i>Previously, opurdila (Octavian Purdila) wrote…</i></summary>
> Hm, maybe I am missing something, but if we already mounted the fs, then we already created the directory and lkl_sys_mkdir above is going to fail.
</details>
yes. in that case ret = -LKL_EEXIST. i still call sys_mount because it can always mount to an existing dir. But if the fs is already mounted, sys_mount returns EBUSY. which is handled at the end of function

---

*[tools/lkl/lib/net.c, line 388 \[r3\]](https://reviewable.io:443/reviews/lkl/linux/197#-KP5OxnrITDyEzQMgB62:-KP5Zj-94UrUnvtHhIvD:bucd0u7) ([raw file](https://github.com/lkl/linux/blob/2276fa72daaf65ca03d68b8becac20a701a617be/tools/lkl/lib/net.c#L388)):*
<details><summary><i>Previously, opurdila (Octavian Purdila) wrote…</i></summary>
> I think there is a race condition here, if DAD completed before we call wait_ipv6 we will hang here forever.
</details>
good catch. added a get addr request so it can always receive a msg to check if the addr is tentative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/197)*

**Comment by opurdila** [comment]
:lgtm:

One last thing, should we change the fprintf bits to lkl_printf, to be consistent with the rest of the code and host independent?

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/197#-:-KP7oHbhK01VVsxlVfvb:b-pdb1r2)*

**Comment by liuyuan10** [comment]
Done.

---

Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/197#-:-KPA1s3ljELtscV6Im-T:b-896fix)*

**Comment by opurdila** [comment]
Thanks!

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/197#-:-KPA6SyBaJ5VQiN-ZExB:b-ucfknh)*

**Pull request merged**
