### PR TITLE
Migration to CircleCI 2.0

### PR DESCRIPTION
**Pull request by thehajime**
This is a PR to migrate our CI test infra to CircleCI 2.0 (https://circleci.com/docs/2.0/).  It is almost working better than previous one, but one concern is we have no capability to open PF_PACKET/RAW socket during the test (`ping` command says `icmp open socket: Operation not permitted`, so `tests/net-test` is skipped).  Other tests which we have done with the previous setup are properly working: android-aarch64 is now tested.

I crafted a custom docker image (https://github.com/thehajime/lkl-docker): we can update those image in a future if we want to include something in the image.

---
This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/378)

### CODE REVIEW

**Comment by thehajime** [comment]
ping @tavip ?

**Comment by tavip** [comment]
Sorry, this flew under my radar. Looks good to me.

Too bad that we need to drop the PF_PACKET test. Does fuse work now? I did a quick check on TravisCI and it seems to be supported there. Do you think it is worth investigating moving  to TravisCI?

**Comment by thehajime** [comment]
> Too bad that we need to drop the PF_PACKET test. Does fuse work now? I did a quick check on TravisCI and it seems to be supported there. Do you think it is worth investigating moving to TravisCI?

I tried and it seems that fuse isn't still available on circleci.

I have both experience with travis-ci and circle-ci, and my tentative conclusion is both have pros/cons (thus, I have no preference) :)

Here are my observations.

- Travis is friendly to have matrix tests, though circleci 2.0 is a bit improved by workflow in this feature.
- Travis often failed with unknown reason, is unstable, but circleci does also.
- CircleCI can debug with ssh login into a test instance, while Travis can only with paid plan (not sure?).
both Travis and Circle don't have tap device support. fuse support on Travis is new to me (it's good to go).
- Pre-packed docker image (this PR) for new CirecleCI 2.0 is really useful, though I'm not sure that TravisCI does have smtg like this.  This also contributes shorter test time.

**Comment by thehajime** [comment]
thanks for the review, @tavip.

**Pull request merged**
