### PR TITLE
lklfuse filesystem options

### LINKED ISSUE #203: filesystem specific options
Just got lklfuse to work in FreeBSD 11.0, but cannot mount btrfs partitions with subvolumes.
Maybe that would be possible if filesystem specific mounting options would be implemented, like subvolid=xxx,discard,autodefrag etc.
Any plans for that?
Thanks,
eu41

### PR DESCRIPTION
**Pull request by ghost**
This fixes #203

---

This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/205)

### CODE REVIEW

**Comment by eu41** [comment]
Tried this and it's not working:

lklfuse -d -o type=btrfs,opts=subvolid\=258\,space_cache\,autodefrag

Fails with message:

Unknown option 'opts=subvolid=258,space_cache,autodefrag'

**Comment by opurdila** [comment]
As mentioned on the issue, you need to use double escapes:

`
./lklfuse -d -o type=ext4,opts=discard\\,max_batch_time\\=10 system-unsparse.img ~/mnt
`

Pushed a new version that fixes checkpatch.pl errors.

**Comment by eu41** [comment]
Octavian,

I will try this evening at home with double quotes.
But will not be able to apply your patch: I'm using lklfuse as part of FreeBSD ports fusefs-lkl and not sure that they update their ports that often to get the latest from github.
Will let you know.

**Comment by cemeyer** [comment]
Hi,

I'm the maintainer of the FreeBSD port.  I'm happy to pull this in to the port after it lands in master.  For what it's worth, both patches look fine to me.  I haven't tested it.

**Pull request merged**
