### PR TITLE
Merge 4.6-rc5

### PR DESCRIPTION
**Pull request by ghost**
This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/153)

### CODE REVIEW

**Comment by opurdila** [comment]
This is just a heads up and work in progress. In 4.6 virtio depends on CONFIG_HAS_DMA and because we don't have it implemented in LKL all I/O test (disk, networking) fail. I've started to put something together a dma-mapping implementation for LKL and hope to have something by EOW.

**Comment by thehajime** [comment]
great ! this is what I'm so much waiting for.

**Comment by opurdila** [comment]
Tests fixed,  @thehajime @pscollins @stfairy could you please take a look?

**Comment by liuyuan10** [comment]
After patching this PR, I still get the same error as commit [https://github.com/opurdila/linux/commit/51c0f8bf91fc12db898c054e51450e91c6636f06](url). Looks like the newly added arch/lkl/include/uapi/asm/siginfo.h is not included in compilation. Am I missing anyting?

**Comment by opurdila** [comment]
@liuyuan10 you need to do a make mrproper, otherwise the new siginfo.h is not used.

**Comment by pscollins** [comment]
Looks fine to me. I'm not totally clear what's going on --- virtio depends on `HAS_DMA` now, but it just needs a dummy implementation to get it to compile? I guess the reason the dependency was added was so that arch-specific virtio drivers could take advantage of it if they want to, but LKL doesn't need to?

**Comment by opurdila** [comment]
Quoting from the upstream virtio commit: 
    
    "virtio_ring currently sends the device (usually a hypervisor)
    physical addresses of its I/O buffers.  This is okay when DMA
    addresses and physical addresses are the same thing, but this isn't
    always the case."

In our case the DMA address is the same with the physical address so we can use the DMA noop implementation.

**Comment by thehajime** [comment]
I've tested basic tests (make test + a bit) and looks fine.  I wanted to test with my musl branch but will do later after this PR.

+1.

thanks again.

**Pull request merged**
