### PR TITLE
lkl tools: fix to report test failure

### PR DESCRIPTION
**Pull request by thehajime**
Fixes: f0eab6e86af8 ("lkl: Fix INSTALL_PATH error, add more test options")
Signed-off-by: Hajime Tazaki thehajime@gmail.com

[Review on Reviewable](https://reviewable.io/reviews/lkl/linux/57)

### CODE REVIEW

**Comment by thehajime** [comment]
cc: @pscollins (regression in #49).

**Comment by pscollins** [comment]
Oh, whoops, it didn't occur to me that something else might be relying on the error code returned by `make test`. It looks to me like this will cause the whole test suite to stop early if one of the tests fails, though, is that what we want? That seems different from what the original behavior was.

**Comment by thehajime** [comment]
> Oh, whoops, it didn't occur to me that something else might be relying on the error code returned by make test.

especially our CI test (i.e., circleci) depends on the return value.


> It looks to me like this will cause the whole test suite to stop early if one of the tests fails, though, is that what we want? That seems different from what the original behavior was.

- an individual test _inside_ ```boot.c``` keeps running after a failure.
- but a failure from ```./boot``` stops the whole ```make test```

I think this is the original behavior.

but I agree with you: I'm not sure whether this is what we want. maybe we need a switch to whether ```make test``` will stop or not after a failure.

**Comment by pscollins** [comment]
Ah, okay, makes sense. LGTM, thanks for clearing that up! In a future world the best thing to do would probably be to emit all of the test output in XUnit format so that CircleCI can understand it all, but that's maybe more work than is needed right now.

**Comment by opurdila** [comment]
Thanks Hajime and Patrick, I am going to merge the pull request now.

**Pull request merged**
