### PR TITLE
add lkl_netdev_args to consolidate signature of lkl_netdev_add

### PR DESCRIPTION
**Pull request by liuyuan10**
This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/190)

### CODE REVIEW

**Comment by hkchu** [comment]
What's the purpose for this change? (Note that "offload" is meant only to program additional features. The complete feature set is kept and available from the kernel already.)

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/190#-:-KOGmb18ZD0lPPZUM7M5:-1766305695)*

**Comment by liuyuan10** [comment]
lkl_netdev_add is heavily used by users of LKL so changing the signature is painful. I made a new change that consolidates all arguments into a struct so future args won't break existing application. PTAL

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/190#-:-KOH59L3jvBToEB8BMl4:337158065)*

**Comment by hkchu** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/190#-:-KOH6UYzLJ8NYWhTTPwz:1417088721)*

**Comment by opurdila** [comment]
Reviewed 3 of 10 files at r1, 3 of 5 files at r2.
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lkl/include/lkl.h, line 255 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/190#-KOHPP4tDZFyCa8chb7s:-KOHPP4tDZFyCa8chb7t:-417550815) ([raw file](https://github.com/lkl/linux/blob/f45cd651ad2e36431c926db3f8d78661dd857b98/tools/lkl/include/lkl.h#L255)):*
> ```objc
> struct lkl_netdev_args {
> 	void *mac;
>  	unsigned int offload;
> ```

Small coding style issue, space at the beginning of the line.

---

*[tools/lkl/lib/hijack/init.c, line 302 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/190#-KOHPCqpIigM765mf5NB:-KOHPCqqAVSGTvzLy46e:-1599050076) ([raw file](https://github.com/lkl/linux/blob/f45cd651ad2e36431c926db3f8d78661dd857b98/tools/lkl/lib/hijack/init.c#L302)):*
> ```C
> 			"LKL_HIJACK_NET_IFPARAMS instead.\n");
> 		nd = lkl_netdev_tap_create(tap, offload);
> 		if (nd) nd_args.offload = offload;
> ```

Small coding style issue, initialization should be on next line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/190)*

**Comment by liuyuan10** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lkl/include/lkl.h, line 255 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/190#-KOHPP4tDZFyCa8chb7s:-KOHQyGSEjuLfb5_vKzm:-499146009) ([raw file](https://github.com/lkl/linux/blob/f45cd651ad2e36431c926db3f8d78661dd857b98/tools/lkl/include/lkl.h#L255)):*
<details><summary><i>Previously, opurdila (Octavian Purdila) wrote…</i></summary>
> Small coding style issue, space at the beginning of the line.
</details>
Done.

---

*[tools/lkl/lib/hijack/init.c, line 302 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/190#-KOHPCqpIigM765mf5NB:-KOHR5NiHmxJ2Aj0nNng:-499146009) ([raw file](https://github.com/lkl/linux/blob/f45cd651ad2e36431c926db3f8d78661dd857b98/tools/lkl/lib/hijack/init.c#L302)):*
<details><summary><i>Previously, opurdila (Octavian Purdila) wrote…</i></summary>
> Small coding style issue, initialization should be on next line.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/190)*

**Comment by opurdila** [comment]
:lgtm:

---

Reviewed 2 of 10 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/190#-:-KOHSMFUlW45zC1GuC6A:1417088721)*

**Comment by opurdila** [comment]
@thehajime could you also please take a look?

**Comment by thehajime** [comment]
:lgtm:
Only a single minor issue. 

---

Reviewed 5 of 10 files at r1, 1 of 5 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[tools/lkl/include/lkl.h, line 256 \[r3\]](https://reviewable.io:443/reviews/lkl/linux/190#-KOI26f7fF1Qm1yePjL1:-KOI26f7fF1Qm1yePjL2:489222873) ([raw file](https://github.com/lkl/linux/blob/21a27e8594b1f0938baa0cf0d7c922debf4896ae/tools/lkl/include/lkl.h#L256)):*
> ```objc
> 	void *mac;
> 	unsigned int offload;
>  };
> ```

There is still a space at the beginning. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/190#-:-KOI2S850ANd5sI2bYb_:-2090578110)*

**Comment by liuyuan10** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tools/lkl/include/lkl.h, line 256 \[r3\]](https://reviewable.io:443/reviews/lkl/linux/190#-KOI26f7fF1Qm1yePjL1:-KOI3Ofx4-NHGjW7P1o6:1956711134) ([raw file](https://github.com/lkl/linux/blob/21a27e8594b1f0938baa0cf0d7c922debf4896ae/tools/lkl/include/lkl.h#L256)):*
<details><summary><i>Previously, thehajime (Hajime Tazaki) wrote…</i></summary>
> There is still a space at the beginning. 
</details>
Oops. Thanks for catching it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/190)*

**Pull request merged**
