### PR TITLE
lkl: Add proper memory barrier to virtio.c

### PR DESCRIPTION
**Pull request by liuyuan10**
I don't see any bugs caused by this but theoretically a memory barrier
is needed before updating ring idx and triggering irq.

Signed-off-by: Yuan Liu liuyuan@google.com

---

This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/151)

### CODE REVIEW

**Comment by liuyuan10** [comment]
I'm not sure if I should be using "include/asm-generic/barrier.h". I guess that's for kernel but virtio.c is user space code.

Please let me if you know better mem barrier to use.

**Comment by pscollins** [comment]
LGTM. I think `include/asm-generic/barrier.h` is unncessarily heavy weight for this, and by way of `include/linux/compiler.h` it will pull in: 

```
#ifdef CONFIG_PROFILE_ALL_BRANCHES
...
#define if(cond, ...) __trace_if( (cond , ## __VA_ARGS__) )
#define __trace_if(cond) \
        if (__builtin_constant_p((cond)) ? !!(cond) :                   \
        ({                                                              \
                int ______r;                                            \
                static struct ftrace_branch_data                        \
                        __attribute__((__aligned__(4)))                 \
                        __attribute__((section("_ftrace_branch")))      \
                        ______f = {                                     \
                                .func = __func__,                       \
                                .file = __FILE__,                       \
                                .line = __LINE__,                       \
                        };                                              \
                ______r = !!(cond);                                     \
                ______f.miss_hit[______r]++;                                    \
                ______r;                                                \
        }))
#endif /* CONFIG_PROFILE_ALL_BRANCHES */
```

which could cause some frustration down the line if someone wants to turn on `CONFIG_PROFILE_ALL_BRANCHES`.

It might be nice to pull this and some of the other `__sync` functions we use into one file, `lkl-atomic.h` or something like that, which would make it easy to change them in the future. But it's probably more trouble than it's worth right now.

**Comment by opurdila** [comment]
I agree with @pscollins , lets stick with __sync for now. It its not much trouble I would even remove the smp_mb() define. We probably need to create proper lkl userspace abstractions (the lkl-atomic.h @pscollins mentioned) but for now lets go directly with the  _sync_*  builtins.

**Comment by liuyuan10** [comment]
@opurdila Removed smp_mb define

**Pull request merged**
