### PR TITLE
lkl: update build documentation for mingw / Windows

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Octavian Purdila octavian.purdila@intel.com

---

This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/216)

### CODE REVIEW

**Comment by Rondom** [comment]
Have you tested this?

**Comment by opurdila** [comment]
I tested the Linux/mingw part. Its only updates to the Documentation so it should not break anything even on the Windows host build. Did you notice any issues?

**Comment by Rondom** [comment]
I only tried building on Windows once out of curiosity quite some time ago and it did not work (due to some symlink-issue I think).  I did not investigate it further because I am more comfortable with Linux and cross-compiling serves me well and is much  faster.

Sure, updating the documentation is fine and of course it does not break anything. I was only curious whether you tested building on Windows due to the above. I might test again when I have time but that is unfortunately not now :-(

**Comment by staalmannen** [comment]
Last time I tried to build it on Windows I ran it under Msys2 and that worked fine. I have not had time to play much more though :( 

(I was planning to try to get the clang-patched lkl branch to build with ClangC2 to make native MSVC libraries... but never got very far...)

My windows experiments have however stopped since it is very slow on my weak computer in a VM.

**Pull request merged**
