### PR TITLE
virtio cleanups

### PR DESCRIPTION
**Pull request by ghost**
This PR adds a few helper functions to make the merge buffer code easier to follow. It also removes the network specific code out of the core virtio code, fixes a few coding style issues and switches to struct iovec and removing lkl_dev_buf as was suggested some time ago.

---

This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/217)

### CODE REVIEW

**Comment by hkchu** [comment]
*[tools/lkl/lib/virtio.c, line 198 \[r1\]](https://reviewable.io:443/reviews/lkl/linux/217#-KQ8XZKQDPRdArDhlqdh:-KQ8XZKRKzpfLOiLVIB2:b-fquk04) ([raw file](https://github.com/lkl/linux/blob/1d51bd81c9644fa9990ffacbba0899cfc0424f79/tools/lkl/lib/virtio.c#L198)):*
> ```C
> 	struct lkl_vring_desc *curr_vring_desc = vring_desc_at_le_idx(q, req.idx);
> 
> 	if (is_mergeable_rx) {
> ```

The original code guarded by "is_mergeable_rx" is only applicable for RX but it looks like now with the above if-statement removed the following code will be executed for TX as well. Is that intended?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/217)*

**Comment by opurdila** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/lkl/lib/virtio.c, line 134 \[r1\]](https://reviewable.io:443/reviews/lkl/linux/217#-KQA5FFpgImzoecvvfcW:-KQA5FFpgImzoecvvfcX:b3rrpt4) ([raw file](https://github.com/lkl/linux/blob/362035840cbff3a9f54e5fba264501758436f923/tools/lkl/lib/virtio.c#L134)):*
> ```C
> 
> 		if (!q->max_merge_len)
> 			used_len = len;
> ```

This will break the loop after the first iteration if q->max_merge_len is not set (len - (used_len=len) == 0).

Should I add a comment for that, or is it clear enough?

---

*[tools/lkl/lib/virtio.c, line 198 \[r1\]](https://reviewable.io:443/reviews/lkl/linux/217#-KQ8XZKQDPRdArDhlqdh:-KQA4Wfd1xYZD8PpYiDt:bj2mfe2) ([raw file](https://github.com/lkl/linux/blob/1d51bd81c9644fa9990ffacbba0899cfc0424f79/tools/lkl/lib/virtio.c#L198)):*
<details><summary><i>Previously, hkchu (Jerry Chu) wrote…</i></summary>
> The original code guarded by "is_mergeable_rx" is only applicable for RX but it looks like now with the above if-statement removed the following code will be executed for TX as well. Is that intended?
</details>
q->max_merge_len is only set for the RX queue and that check is still performed in get_next_desc .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/217)*

**Comment by liuyuan10** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/lkl/include/lkl_host.h, line 23 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/217#-KQM4Ia-5I8gwT4kS3XO:-KQM4Ia0scYnVaoXvKAI:b-fkuz0k) ([raw file](https://github.com/lkl/linux/blob/5f6e08a5512b3f3cd5c7dd15fd0966acaf1a97d5/tools/lkl/include/lkl_host.h#L23)):*
> ```objc
> 
> #ifdef CONFIG_AUTO_LKL_POSIX_HOST
> #include <sys/uio.h>
> ```

Just curious. why can't we use "lkl/linux/uio.h"?

---

*[tools/lkl/lib/virtio.c, line 137 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/217#-KQMEKK3n6x_e9X6W5LJ:-KQMEKK410UqUZm9Ssvy:bh0zgji) ([raw file](https://github.com/lkl/linux/blob/5f6e08a5512b3f3cd5c7dd15fd0966acaf1a97d5/tools/lkl/lib/virtio.c#L137)):*
> ```C
> 			used_len = min_len(len,  req->buf[i].iov_len);
> 
> 		len -= virtio_add_used(q, used_idx++, avail_idx++, used_len);
> ```

I think it's clearer to directly do "len -= used_len?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/217)*

**Comment by opurdila** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[tools/lkl/include/lkl_host.h, line 23 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/217#-KQM4Ia-5I8gwT4kS3XO:-KQMuS8Ga3sYGc1QVr_5:b-ocop5n) ([raw file](https://github.com/lkl/linux/blob/5f6e08a5512b3f3cd5c7dd15fd0966acaf1a97d5/tools/lkl/include/lkl_host.h#L23)):*
<details><summary><i>Previously, liuyuan10 (Yuan Liu) wrote…</i></summary>
> Just curious. why can't we use "lkl/linux/uio.h"?
</details>
Not  a bad idea. But that will still require a build check since size_t may be different between LKL and host and will still need a cast.

---

*[tools/lkl/lib/virtio.c, line 137 \[r2\]](https://reviewable.io:443/reviews/lkl/linux/217#-KQMEKK3n6x_e9X6W5LJ:-KQMze4CYCqJkLGprzXQ:b32w1t) ([raw file](https://github.com/lkl/linux/blob/5f6e08a5512b3f3cd5c7dd15fd0966acaf1a97d5/tools/lkl/lib/virtio.c#L137)):*
<details><summary><i>Previously, liuyuan10 (Yuan Liu) wrote…</i></summary>
> I think it's clearer to directly do "len -= used_len?
</details>
Ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/217)*

**Comment by liuyuan10** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/217#-:-KQRJNmFE1lbNJYxcISk:bnfp4nl)*

**Comment by opurdila** [comment]
Thanks for the review @liuyuan10 . I will wait for a lgtm from @hkchu before merging, as this is complex code and I don't want to break it :)

**Comment by hkchu** [comment]
Sorry for the delay - it's a lot of rewrites and i don't have time to go through all of them but they look fine (as long as it works).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/lkl/linux/217#-:-KQX7RQEaSAgHun5dXx8:b71zpl0)*

**Pull request merged**
